version: 2
sources:
    - name: airstats
      schema: raw
      tables: 
        - name: airports

          identifier: airports
        
        - name: runways
          identifier: runways
        
        - name: airport_comments
          identifier: airport_comments
          
